---
sidebar: sidebar 
permalink: concept_licensing.html 
keywords: licenses, standard, premium, features, licensing, alerts, notifications, emails, reports, term, subscription, reporting 
summary: Converged Systems Advisor の機能をロック解除するにはライセンスが必要です。FlexPod コンバージドインフラごとに、いくつかのライセンスオプションから選択できます。 
---
= ライセンス
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Converged Systems Advisor の機能をロック解除するにはライセンスが必要です。FlexPod コンバージドインフラごとに、いくつかのライセンスオプションから選択できます。

[cols="12,64,24"]
|===
| 使用許諾 | の機能 | 利用規約 


| ライセンスなし  a| 
製品の機能を示す限定バージョン：

* FlexPod 構成の監視を 24 時間試用期間で実施
* FlexPod のベストプラクティスに準拠しているかどうかを表示するヘルスダッシュボード
* インベントリと修復に制限がある（ライセンス版で利用可能）

 a| 
* 無料
* シングルユース（ 24 時間）




| 標準  a| 
* FlexPod 構成の継続的な監視
* FlexPod のベストプラクティスに準拠しているかどうかを表示するヘルスダッシュボード
* コンピューティング、ネットワーク、ストレージ、ハイパーバイザー用のファームウェアの相互運用性
* 変更を識別し、構成のずれを防止するライフサイクル管理ツール
* 高度なトラブルシューティングのための詳細なインベントリとシステム図
* ネットアップから直接提供されるサポート

 a| 
サブスクリプションベースのライセンス：

* 最低 12 か月
* 最大 60 カ月




| Premium サービス  a| 
Standard ライセンスに含まれるすべての機能に加えて、次の機能が含まれます。

* レポート作成
+
FlexPod の健全性、相互運用性、およびインベントリに関する包括的なリアルタイムレポート

* 通知とアラート
+
設定の健全性とステータスの変化を定期的に通知します


 a| 
サブスクリプションベースのライセンス：

* 最低 12 か月
* 最大 60 カ月


|===