---
sidebar: sidebar 
permalink: task_deployment_validation_partners_resellers.html 
keywords: review, alerts, warnings, failed, rules, alerts, history, remediate, remediation, suppress, display, fail, warning, pass, notifications, email 
summary: パートナー様やリセラー様は、お客様のインフラの導入を検証できます。 
---
= パートナーとリセラーの導入を検証します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
パートナー様やリセラー様は、ダッシュボードに表示されるデータを確認するか、健全性レポートを生成することで、お客様のインフラの導入を検証できます。

.を開始する前に
* お客様のサイトに新しい FlexPod をインストールしておくか、既存の FlexPod で作業している。
* FlexPod デバイスでアカウントを作成した。
* TACACS+ サーバを使用している場合は、 CSA ユーザ権限が付与されます。
* エージェントをダウンロードしてインストールした。
+
を参照してください link:task_setup_deploy_agent.html["エージェントをセットアップして配備します"]。

* エージェントのネットワークを設定します。必要に応じて、 SSL 証明書をエージェントにインストールします。
* ネットアップのクレデンシャルを使用して、お客様がインフラをポータルに追加するための CI を作成しました。
+
を参照してください link:task_add_infrastructure["ポータルにインフラストラクチャを追加します"] CSA ポータルで CI を作成します。

* 必要に応じて、他のユーザとインフラを共有しました。


パートナー様とリセラー様は、自社のネットアップクレデンシャルを使用して CSA ポータルにログインし、検証プロセスを開始します。

. にログインします https://csa.netapp.com/["Converged Systems Advisor ポータル"^] ネットアップクレデンシャルを使用する。
. [ * CI の選択 * ] をクリックし、顧客に適した CI をクリックするか、検索ボックスに CI 名を入力します。CI のダッシュボードが表示されます。


パートナー様やリセラー様は、次の方法でお客様のインフラを検証できます。

* ダッシュボードでは、インフラのさまざまな要素を検証できます。
+
** * ファームウェアの相互運用性 * にインストールされているソフトウェアのバージョンが表示されます各見出しをクリックすると、詳細が表示されます。
** * サポート契約 * 契約期限が表示されます。追加情報の [ 詳細の表示 *] をクリックします。
** * エージェントステータス * には、監視対象のデバイスを含むエージェントの詳細が表示されます。
** * 容量 * には、ディスクスペース、ネットワークポート、 UCS ブレードシャーシの使用率が表示されます。各利用率の詳細を表示するには、リンクをクリックします。
** * ヘルス * は、インフラストラクチャのストレージ、コンピューティング、ネットワーク、仮想化機能のルールのステータスをグラフィカルに表示します。グラフィックの色領域をクリックすると、詳細が表示されます。
** * ルールの概要 * には、失敗したルールと警告に関するアラートが表示されます。各行の左側にある矢印をクリックするか、デバイス名をクリックして詳細を確認します。


* アクションバーで、 * レポート -> 正常性レポート * を選択して、詳細な統合システム健全性レポートを生成します。ブラウザで表示したり、 PDF ファイルとしてダウンロードしたり、 E メールで共有したりできます。

